### ISSUE TITLE
Set Jenkins Persistence.StorageClass "-" as default

### ISSUE THREAD

**Issue by JohnNiang** [LinuxSuRen/ks-devops#10]
Currently, default value of Jenkins `Persistence.StorageClass` is "local", which means that we must have a storageclass named "local". This is unreasonable.

https://github.com/LinuxSuRen/ks-devops/blob/781c64c7e93d41b2ee0a66fb50c9f6723a524c69/charts/ks-devops/charts/jenkins/values.yaml#L406

We could make the `storageClassName` field disappear as default by setting `Persistence.StorageClass` as "-".
> https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
> https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass

**Comment by LinuxSuRen** [comment]
Excellent issue. How about just create a PR against this?
