### ISSUE TITLE
有关 devops api 引用不一致的问题

### ISSUE THREAD

**Issue by JohnNiang** [LinuxSuRen/ks-devops#24]
### 问题
在 ks-devops repo 和 kubesphere/api 下我发现了两份不一致的 devops api：

- 本地代码路径：`./pkg/api/devops/**`；

- 远程路径：<https://github.com/kubesphere/api>。

所以，我们具体以哪个为准呢？

**Comment by JohnNiang** [comment]
经过讨论，最终以本地 api 为准。

**Comment by LinuxSuRen** [comment]
So, I guess we can close this issue. If you have more questions about this, please comment here.

**Comment by JohnNiang** [comment]
I just want to close this issue by making a pull request to resolve inconsistent api.
